# Generated by Django 5.1.6 on 2025-03-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_options_alter_obra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='valor_obra',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
